// Define the type for icon names
export type Icon =
  | "archive"
  | "arrow-left"
  | "checkmark"
  | "chevron-right"
  | "clock"
  | "cross"
  | "delete"
  | "font-monospace"
  | "font-sans-serif"
  | "font-serif"
  | "font"
  | "google"
  | "hide-password"
  | "home"
  | "info"
  | "lock"
  | "logout"
  | "menu"
  | "moon"
  | "plus"
  | "restore"
  | "search"
  | "settings"
  | "show-password";
